dist: xenial

language: python

sudo: true

git:
  depth: 1

env:
  global:

    - GDALINST=$HOME/gdalinstall
    - GDALBUILD=$HOME/gdalbuild
    - PROJINST=$HOME/projinstall
    - PROJBUILD=$HOME/projbuild
    - GHPAGESDIR=$HOME/ghpages
    #- FORCE_BUILD="yes"

jobs:
  include:

    - stage:  "GDAL 1.11.x"
      env:
        - PROJVERSION="4.8.0"
        - GDALVERSION="1.11.5"

    - stage:  "GDAL 2.0.x"
      env:
        - PROJVERSION="4.9.3"
        - GDALVERSION="2.0.3"

    - stage:  "GDAL 2.1.x"
      env:
        - PROJVERSION="4.9.3"
        - GDALVERSION="2.1.4"
        
    - stage:  "GDAL 2.2.x"
      env:
        - PROJVERSION="4.9.3"
        - GDALVERSION="2.2.4"

    - stage:  "GDAL 2.3.x"
      env:
        - PROJVERSION="4.9.3"
        - GDALVERSION="2.3.3"

    - stage:  "GDAL 2.4.x"
      env:
        - PROJVERSION="4.9.3"
        - GDALVERSION="2.4.2"

    - stage:  "GDAL 2.5.x"
      env:
        - PROJVERSION="6.1.1"
        - GDALVERSION="2.5.0rc1"

    - stage:  "GDAL 3.0.x"
      env:
        - PROJVERSION="6.1.1"
        - GDALVERSION="3.0.1"

    - stage:  "master"
      env:
        - PROJVERSION="6.1.1"
        - GDALVERSION="master"

addons:
  apt:
    packages:
    - libhdf5-serial-dev
    - libatlas-dev
    - libatlas-base-dev
    - gfortran
    - libsqlite3-dev
    - sqlite3

before_install:
  - export DISTRIB_CODENAME=$(lsb_release -cs)
  - export PATH=$GDALINST/gdal-$GDALVERSION/bin:$PROJINST/proj-$PROJVERSION/bin:$PATH
  - export LD_LIBRARY_PATH=$GDALINST/gdal-$GDALVERSION/lib:$PROJINST/proj-$PROJVERSION/lib:$LD_LIBRARY_PATH
  - export GDAL_DATA=$GDALINST/gdal-$GDALVERSION/share/gdal
  - export PROJ_LIB=$PROJINST/proj-$PROJVERSION/share/proj

  - git clone -b --depth=1 --single-branch --branch gh-pages https://github.com/rbuffat/gdal_builder.git $GHPAGESDIR
  - rm -rf $GHPAGESDIR/.git

install:
  - . ./scripts/build_proj.sh
  - . ./scripts/build_gdal.sh
  - . ./scripts/check_files.py $PROJINST
  - . ./scripts/check_files.py $GDALINST
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: false
  local_dir: $HOME/ghpages
  on:
    branch: master
