dist: xenial

language: minimal

sudo: true

env:
  global:
    - GDAL_VERSIONS="2.3.3 2.4.2"
    - GDALINST=$HOME/gdalinstall
    - GDALBUILD=$HOME/gdalbuild
    - GHPAGESDIR=$HOME/ghpages

addons:
  apt:
    packages:
    - libhdf5-serial-dev
    - libatlas-dev
    - libatlas-base-dev
    - gfortran
    - libsqlite3-dev
    - sqlite3
    - checkinstall
    
install:
  - . ./scripts/build_gdal.sh
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: $HOME/ghpages
  on:
    branch: master
