dist: xenial

sudo: true

env:
  global:
    - PROJVERSION="6.0.0"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y checkinstall build-essential automake autoconf libtool pkg-config libhdf5-serial-dev libatlas-dev libatlas-base-dev gfortran libsqlite3-dev sqlite3

install:
  - . ./scripts/build_proj.sh
