language: python

dist: xenial

python:
  - "3.6"

git:
  depth: 1

env:
  global:
    - GDALINST=$HOME/gdalinstall
    - GDALBUILD=$HOME/gdalbuild
    - PROJINST=$HOME/gdalinstall
    - PROJBUILD=$HOME/projbuild

jobs:
  include:

    - stage:  "master"
      env:
        - PROJVERSION="6.2.1"
        - GDALVERSION="master"

addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - gfortran
    - libsqlite3-dev
    - sqlite3

before_install:

  - git clone -b --depth=1 --single-branch --branch gh-pages https://github.com/rbuffat/gdal_builder.git $GHPAGESDIR
  - rm -rf $GHPAGESDIR/.git
  - export DISTRIB_CODENAME=$(lsb_release -cs)
  - export PATH=$GDALINST/gdal-$GDALVERSION/bin:$GDALINST/proj-$PROJVERSION/bin:$PATH
  - export LD_LIBRARY_PATH=$GDALINST/gdal-$GDALVERSION/lib:$GDALINST/proj-$PROJVERSION/lib:$LD_LIBRARY_PATH
  - . ./scripts/travis_proj_install.sh
  - . ./scripts/travis_gdal_install.sh
  - export GDAL_DATA=$GDALINST/gdal-$GDALVERSION/share/gdal
  - export PROJ_LIB=$GDALINST/gdal-$GDALVERSION/share/proj
  - gdal-config --version

install: true

#script:
  #- python scripts/check_files.py $PROJINST
  #- python scripts/check_files.py $GDALINST

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: false
  local_dir: $HOME/ghpages
  on:
    branch: master
